// ============================================
// HS Generator ML - Zain Developer
// Frontend Application
// ============================================

class HSGeneratorBackend {
    constructor() {
        this.apiEndpoint = '/api/upload';
        this.mockMode = true; // Set false untuk mode production dengan Cloudinary
    }
    
    // Simulate Cloudinary upload (mock mode)
    async uploadToCloudinary(imageFile) {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                // Simulate successful upload
                this.createMockResult(imageFile)
                    .then(mockUrl => {
                        resolve({
                            success: true,
                            url: mockUrl,
                            public_id: `zain-hs/${Date.now()}`,
                            width: 1200,
                            height: 800,
                            format: 'jpg',
                            bytes: imageFile.size
                        });
                    })
                    .catch(error => reject(error));
            }, 1500);
        });
    }
    
    // Create mock result image with enhancement
    async createMockResult(imageFile) {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onload = (e) => {
                const img = new Image();
                img.onload = () => {
                    const canvas = document.createElement('canvas');
                    const ctx = canvas.getContext('2d');
                    
                    // Set canvas size (max 1200px width)
                    canvas.width = Math.min(img.width, 1200);
                    canvas.height = img.height * (canvas.width / img.width);
                    
                    // Draw original image
                    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
                    
                    // Apply enhancements (simulate HS showcase)
                    this.applyShowcaseEffects(ctx, canvas);
                    
                    // Convert to data URL
                    const resultUrl = canvas.toDataURL('image/jpeg', 0.9);
                    resolve(resultUrl);
                };
                img.onerror = () => reject(new Error('Gagal memuat gambar'));
                img.src = e.target.result;
            };
            reader.onerror = () => reject(new Error('Gagal membaca file'));
            reader.readAsDataURL(imageFile);
        });
    }
    
    // Apply showcase effects to image
    applyShowcaseEffects(ctx, canvas) {
        // Add subtle vignette effect
        const gradient = ctx.createRadialGradient(
            canvas.width / 2, canvas.height / 2, 0,
            canvas.width / 2, canvas.height / 2, Math.max(canvas.width, canvas.height) / 2
        );
        gradient.addColorStop(0, 'rgba(0,0,0,0)');
        gradient.addColorStop(1, 'rgba(0,0,0,0.3)');
        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        
        // Add HS badge overlay
        ctx.fillStyle = 'rgba(245, 158, 11, 0.9)';
        ctx.fillRect(canvas.width - 180, 20, 160, 40);
        
        ctx.font = 'bold 20px Poppins, sans-serif';
        ctx.fillStyle = 'white';
        ctx.textAlign = 'center';
        ctx.fillText('HS SHOWCASE', canvas.width - 100, 45);
        
        // Add Zain Developer watermark
        ctx.font = '14px Poppins, sans-serif';
        ctx.fillStyle = 'rgba(255,255,255,0.5)';
        ctx.textAlign = 'right';
        ctx.fillText('Generated by Zain Developer', canvas.width - 20, canvas.height - 20);
    }
    
    // Handle upload request
    async handleUpload(formData) {
        try {
            const imageFile = formData.get('image');
            
            if (!imageFile) {
                throw new Error('Tidak ada file gambar yang dipilih');
            }
            
            // Validate file
            if (!imageFile.type.startsWith('image/')) {
                throw new Error('File harus berupa gambar');
            }
            
            if (imageFile.size > 5 * 1024 * 1024) {
                throw new Error('Ukuran file maksimal 5MB');
            }
            
            // Upload to Cloudinary (or mock)
            const result = await this.uploadToCloudinary(imageFile);
            
            return {
                status: 200,
                body: JSON.stringify(result)
            };
            
        } catch (error) {
            console.error('Upload error:', error);
            return {
                status: 500,
                body: JSON.stringify({
                    success: false,
                    error: error.message
                })
            };
        }
    }
}

// ============================================
// FRONTEND APPLICATION
// ============================================

class HSGeneratorApp {
    constructor() {
        // Initialize backend
        this.backend = new HSGeneratorBackend();
        
        // DOM Elements
        this.elements = {
            fileInput: document.getElementById('fileInput'),
            uploadBtn: document.getElementById('uploadBtn'),
            uploadArea: document.getElementById('uploadArea'),
            imagePreview: document.getElementById('imagePreview'),
            placeholderImage: document.getElementById('placeholderImage'),
            fileInfo: document.getElementById('fileInfo'),
            generateBtn: document.getElementById('generateBtn'),
            resetBtn: document.getElementById('resetBtn'),
            resultSection: document.getElementById('resultSection'),
            resultImage: document.getElementById('resultImage'),
            downloadBtn: document.getElementById('downloadBtn'),
            newUploadBtn: document.getElementById('newUploadBtn'),
            loading: document.getElementById('loading'),
            notification: document.getElementById('notification')
        };
        
        // State
        this.state = {
            selectedFile: null,
            resultImageUrl: '',
            isProcessing: false
        };
        
        // Initialize
        this.init();
    }
    
    init() {
        this.bindEvents();
        this.showWelcomeNotification();
        this.addDebugInfo();
    }
    
    bindEvents() {
        // Upload events
        this.elements.uploadBtn.addEventListener('click', () => this.elements.fileInput.click());
        this.elements.uploadArea.addEventListener('click', () => this.elements.fileInput.click());
        this.elements.fileInput.addEventListener('change', (e) => this.handleFileSelect(e));
        
        // Button events
        this.elements.generateBtn.addEventListener('click', () => this.generateHS());
        this.elements.resetBtn.addEventListener('click', () => this.resetUpload());
        this.elements.downloadBtn.addEventListener('click', () => this.downloadResult());
        this.elements.newUploadBtn.addEventListener('click', () => this.resetUpload());
        
        // Drag and drop
        this.elements.uploadArea.addEventListener('dragover', (e) => {
            e.preventDefault();
            this.elements.uploadArea.style.borderColor = 'var(--primary)';
            this.elements.uploadArea.style.background = 'rgba(124, 58, 237, 0.1)';
        });
        
        this.elements.uploadArea.addEventListener('dragleave', () => {
            this.elements.uploadArea.style.borderColor = 'rgba(124, 58, 237, 0.3)';
            this.elements.uploadArea.style.background = 'transparent';
        });
        
        this.elements.uploadArea.addEventListener('drop', (e) => {
            e.preventDefault();
            this.elements.uploadArea.style.borderColor = 'rgba(124, 58, 237, 0.3)';
            this.elements.uploadArea.style.background = 'transparent';
            
            if (e.dataTransfer.files.length) {
                this.elements.fileInput.files = e.dataTransfer.files;
                this.handleFileSelect();
            }
        });
    }
    
    handleFileSelect() {
        if (!this.elements.fileInput.files.length) return;
        
        this.state.selectedFile = this.elements.fileInput.files[0];
        
        // Validate file
        const validation = this.validateImageFile(this.state.selectedFile);
        if (!validation.valid) {
            this.showNotification(validation.error, 'error');
            return;
        }
        
        // Update UI
        this.elements.fileInfo.textContent = 
            `${this.state.selectedFile.name} (${this.formatFileSize(this.state.selectedFile.size)})`;
        this.elements.generateBtn.disabled = false;
        this.elements.resetBtn.disabled = false;
        
        // Show preview
        this.createImagePreview(this.state.selectedFile, (dataUrl) => {
            this.elements.imagePreview.src = dataUrl;
            this.elements.imagePreview.style.display = 'block';
            this.elements.placeholderImage.style.display = 'none';
        });
    }
    
    async generateHS() {
        if (!this.state.selectedFile || this.state.isProcessing) return;
        
        // Show loading
        this.state.isProcessing = true;
        this.elements.loading.style.display = 'block';
        this.elements.generateBtn.disabled = true;
        
        try {
            // Prepare form data
            const formData = new FormData();
            formData.append('image', this.state.selectedFile);
            
            // Call backend API
            const result = await this.backend.handleUpload(formData);
            const data = JSON.parse(result.body);
            
            if (data.success) {
                this.state.resultImageUrl = data.url;
                this.elements.resultImage.src = data.url;
                
                // Show result section
                setTimeout(() => {
                    this.elements.resultSection.style.display = 'block';
                    this.elements.loading.style.display = 'none';
                    this.state.isProcessing = false;
                    
                    // Scroll to result
                    this.elements.resultSection.scrollIntoView({ 
                        behavior: 'smooth', 
                        block: 'nearest' 
                    });
                    
                    this.showNotification('HS berhasil di-generate!', 'success');
                }, 1000);
            } else {
                throw new Error(data.error || 'Upload gagal');
            }
        } catch (error) {
            this.elements.loading.style.display = 'none';
            this.elements.generateBtn.disabled = false;
            this.state.isProcessing = false;
            this.showNotification(`Error: ${error.message}`, 'error');
            console.error('Error:', error);
        }
    }
    
    resetUpload() {
        this.elements.fileInput.value = '';
        this.state.selectedFile = null;
        this.state.resultImageUrl = '';
        this.state.isProcessing = false;
        
        this.elements.imagePreview.style.display = 'none';
        this.elements.placeholderImage.style.display = 'block';
        this.elements.fileInfo.textContent = 'Belum ada file dipilih';
        this.elements.generateBtn.disabled = true;
        this.elements.resetBtn.disabled = true;
        this.elements.resultSection.style.display = 'none';
        this.elements.loading.style.display = 'none';
    }
    
    downloadResult() {
        if (!this.state.resultImageUrl) return;
        
        // Create a temporary link to download the image
        const link = document.createElement('a');
        link.href = this.state.resultImageUrl;
        link.download = `hs-showcase-${Date.now()}.jpg`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        
        this.showNotification('Download dimulai!', 'success');
    }
    
    // Utility Methods
    formatFileSize(bytes) {
        if (bytes === 0) return '0 Bytes';
        const k = 1024;
        const sizes = ['Bytes', 'KB', 'MB'];
        const i = Math.floor(Math.log(bytes) / Math.log(k));
        return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
    }
    
    validateImageFile(file) {
        const validTypes = ['image/jpeg', 'image/png', 'image/webp', 'image/gif'];
        const maxSize = 5 * 1024 * 1024; // 5MB
        
        if (!validTypes.includes(file.type)) {
            return { valid: false, error: 'Format file tidak didukung' };
        }
        
        if (file.size > maxSize) {
            return { valid: false, error: 'Ukuran file terlalu besar (max 5MB)' };
        }
        
        return { valid: true };
    }
    
    createImagePreview(file, callback) {
        const reader = new FileReader();
        reader.onload = (e) => callback(e.target.result);
        reader.readAsDataURL(file);
    }
    
    showNotification(message, type = 'success') {
        this.elements.notification.textContent = message;
        this.elements.notification.className = `notification ${type}`;
        this.elements.notification.classList.add('show');
        
        setTimeout(() => {
            this.elements.notification.classList.remove('show');
        }, 3000);
    }
    
    showWelcomeNotification() {
        setTimeout(() => {
            this.showNotification('Selamat datang di HS Generator ML! Upload screenshot untuk mulai.', 'success');
        }, 1000);
    }
    
    addDebugInfo() {
        // Add deployment info to page (hidden by default)
        const debugInfo = document.createElement('div');
        debugInfo.className = 'debug-info';
        debugInfo.innerHTML = `
            <strong>Status Aplikasi:</strong><br>
            • Frontend: <span style="color:#22c55e">✓ Berjalan</span><br>
            • Backend API: <span style="color:#22c55e">✓ Mock Mode</span><br>
            • Zain Developer: <span style="color:#22c55e">✓ Active</span><br>
            <button onclick="this.parentNode.style.display='none'" 
                    style="background:#7c3aed;color:white;border:none;padding:5px;margin-top:5px;border-radius:3px;cursor:pointer;width:100%">
                Tutup
            </button>
        `;
        document.body.appendChild(debugInfo);
        
        // Keyboard shortcut to show debug info (Ctrl+Shift+D)
        document.addEventListener('keydown', (e) => {
            if (e.ctrlKey && e.shiftKey && e.key === 'D') {
                debugInfo.style.display = debugInfo.style.display === 'none' ? 'block' : 'none';
            }
        });
    }
}

// ============================================
// INITIALIZE APPLICATION
// ============================================

// Start the application when DOM is loaded
document.addEventListener('DOMContentLoaded', () => {
    // Initialize the app
    const app = new HSGeneratorApp();
    
    // Make app globally accessible for debugging
    window.HSGeneratorApp = app;
    
    // Log welcome message
    console.log('HS Generator ML - Zain Developer');
    console.log('Aplikasi berjalan dengan baik');
    console.log('Gunakan Ctrl+Shift+D untuk info debug');
});